### ISSUE TITLE
Does it save Ammo and inventory items?

### ISSUE THREAD

**Issue by SharpSabre** [rgscriven/Arma-3-Exile-Virtual-Garage#2]
Hello, 
I just ask you: 
Does it save Ammo and inventory items?

**Comment by rgscriven** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Hessam ***@***.***>
Sent: Friday, December 23, 2022 5:51:59 PM
To: rgscriven/Arma-3-Exile-Virtual-Garage ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rgscriven/Arma-3-Exile-Virtual-Garage] Does it save Ammo and inventory items? (Issue #2)


Hello,
I just ask you:
Does it save Ammo and inventory items?
